# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generate_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Password Generator")
        MainWindow.resize(1500, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setWindowIcon(QIcon("icon.png"))
        self.centralWidget = QtWidgets.QWidget(MainWindow)

        self.ButtonGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonGenerate.setGeometry(QtCore.QRect(900, 260, 150, 50))
        self.ButtonGenerate.setObjectName("ButtonGenerate")

        self.ButtonExit = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonExit.setGeometry(QtCore.QRect(900, 630, 150, 50))
        self.ButtonExit.setObjectName("ButtonExit")

        self.ButtonBored = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonBored.setGeometry(QtCore.QRect(900, 530, 150, 50))
        self.ButtonBored.setObjectName("ButtonBored")

        self.ButtonHard = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonHard.setGeometry(QtCore.QRect(900, 450, 150, 50))
        self.ButtonHard.setObjectName("ButtonHard")

        self.number_symbols = QtWidgets.QLineEdit(self.centralwidget)
        self.number_symbols.setGeometry(QtCore.QRect(440, 390, 150, 30))
        self.number_symbols.setObjectName("number_symbols")

        self.number_password = QtWidgets.QLineEdit(self.centralwidget)
        self.number_password.setGeometry(QtCore.QRect(440, 300, 150, 30))
        self.number_password.setObjectName("number_password")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(900, 320, 150, 20))
        self.label.setObjectName("label")

        self.label_passwords = QtWidgets.QLabel(self.centralwidget)
        self.label_passwords.setGeometry(QtCore.QRect(440, 260, 350, 30))
        self.label_passwords.setObjectName("label_passwords")

        self.label_symbols = QtWidgets.QLabel(self.centralwidget)
        self.label_symbols.setGeometry(QtCore.QRect(440, 350, 350, 30))
        self.label_symbols.setObjectName("label_symbols")

        self.label_results = QtWidgets.QLabel(self.centralwidget)
        self.label_results.setGeometry(QtCore.QRect(440, 440, 150, 30))
        self.label_results.setObjectName("label_results")

        self.textPassword = QtWidgets.QTextBrowser(self.centralwidget)
        self.textPassword.setGeometry(QtCore.QRect(440, 480, 300, 200))
        self.textPassword.setObjectName("textPassword")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Generator"))
        self.ButtonGenerate.setText(_translate("ButtonGenerate", "Generate"))
        self.ButtonExit.setText(_translate("ButtonExit", "Exit"))
        self.ButtonBored.setText(_translate("ButtonBored", "Get bored"))
        self.ButtonHard.setText(_translate("ButtonHard", "Life is hard"))
        self.label.setText(_translate("MainWindow", "Generating passwords"))
        self.label_passwords.setText(_translate("MainWindow", "Enter the number of passwords to generate:"))
        self.label_symbols.setText(_translate("MainWindow", "Enter the number of symbols to generate:"))
        self.label_results.setText(_translate("MainWindow", "Results:"))
